<?php

declare(strict_types=1);

namespace InterfaceApi\Support\Generator;

use ReflectionClass;
use ReflectionMethod;
use ReflectionNamedType;
use ReflectionParameter;
use ReflectionProperty;
use ReflectionType;
use ReflectionUnionType;
use InterfaceApi\Support\ApiOperation;
use InterfaceApi\Support\ApiProperty;
use InterfaceApi\Support\ArrayList;
use InterfaceApi\Support\IntToString;
use InterfaceApi\Support\StringToInt;
use InterfaceApi\Support\ValidationRule;
use InterfaceApi\Support\ArrayInteger;
use InterfaceApi\Support\ArrayString;
use InterfaceApi\Support\ApiController;
use InterfaceApi\Support\BaseRequest;
use InterfaceApi\Support\BaseResponse;
use InterfaceApi\Support\Route;
use InterfaceApi\Support\RouteGroup;
use Symfony\Component\Yaml\Yaml;

final class OpenApiDocGenerator
{
    private const DEFAULT_DESCRIPTION = 'Generated by InterfaceApi generate-openapi';
    private const DEFAULT_TITLE_TEMPLATE = '{app} · {module}';
    private const DEFAULT_VERSION = '1.0.0';

    /** @var list<string> */
    private const QUERY_HTTP_METHODS = ['GET', 'HEAD', 'DELETE'];

    /** @var array<string, array{title?: string, description?: string}> */
    private array $moduleMeta = [];

    /** @var array{title: string, description: string, version: string, default_title_template: string} */
    private array $apiDocConfig = [
        'title' => '',
        'description' => '',
        'version' => self::DEFAULT_VERSION,
        'default_title_template' => self::DEFAULT_TITLE_TEMPLATE,
    ];

    private string $appName = 'App';

    public function __construct(
        private string $projectRoot,
        private string $serviceKey,
        private string $outputDir,
        private ?ConsoleReporter $console = null,
    ) {
    }

    public function run(): void
    {
        $started = microtime(true);
        $console = $this->console ?? new ConsoleReporter($this->projectRoot);

        [$appRoot, $moduleRoot, $packageRoot] = $this->resolveServicePaths();
        ProjectBootstrap::register($this->projectRoot);

        $violations = (new ReferenceChecker())->check($appRoot);
        if ($violations !== []) {
            throw new GeneratorException(sprintf('Reference check failed (%d violation(s)).', count($violations)));
        }

        $this->appName = $this->resolveAppName();
        $this->apiDocConfig = $this->loadApiDocConfig();
        $this->moduleMeta = $this->loadModuleMeta($packageRoot);

        $console->banner('InterfaceApi OpenAPI Generator');
        $console->meta('service', $this->serviceKey);
        $console->meta('scan', $console->relPath($moduleRoot));
        $console->meta('output', $console->relPath($this->outputDir));

        $console->section('Collect routes from ApiInterface');
        $routes = $this->collectRoutesFromInterfaces($moduleRoot);
        if ($routes === []) {
            throw new GeneratorException('No #[RouteGroup] routes found under ' . $moduleRoot);
        }
        $console->info(sprintf('collected %d operation(s)', count($routes)));

        $this->ensureDir($this->outputDir);
        $this->cleanGeneratedOpenApiFiles();

        $byModule = [];
        foreach ($routes as $route) {
            $byModule[$route['module']][] = $route;
        }
        ksort($byModule);

        $console->section('Write OpenAPI YAML');
        $written = 0;
        foreach ($byModule as $module => $moduleRoutes) {
            $doc = $this->buildOpenApiDocument($module, $moduleRoutes);
            $file = $this->outputDir . DIRECTORY_SEPARATOR . 'openapi-' . strtolower($module) . '.yaml';
            file_put_contents($file, Yaml::dump($doc, 12, 2, Yaml::DUMP_OBJECT_AS_MAP));
            ++$written;
            $console->ok(
                'openapi-' . strtolower($module) . '.yaml',
                count($moduleRoutes) . ' ops · ' . $console->relPath($file),
            );
        }

        $console->summary(microtime(true) - $started, $written, 0, 0, 'OpenAPI file(s) written');
    }

    /**
     * @return array{0: string, 1: string, 2: string}
     */
    private function resolveServicePaths(): array
    {
        $serviceKey = trim(str_replace('\\', '/', $this->serviceKey), '/');
        if ($serviceKey === '' || (!str_ends_with($serviceKey, '/App') && $serviceKey !== 'App')) {
            throw new GeneratorException('--service must end with /App (e.g. ScheduleJob/App)');
        }

        $interfaceApiRoot = ProjectBootstrap::resolveInterfaceApiRoot($this->projectRoot);
        $appRoot = $interfaceApiRoot
            . DIRECTORY_SEPARATOR . str_replace('/', DIRECTORY_SEPARATOR, $serviceKey);
        if (!is_dir($appRoot)) {
            throw new GeneratorException("App directory not found: {$appRoot}");
        }
        $moduleRoot = $appRoot . DIRECTORY_SEPARATOR . 'Module';
        if (!is_dir($moduleRoot)) {
            throw new GeneratorException("Module directory not found: {$moduleRoot}");
        }

        return [$appRoot, $moduleRoot, dirname($appRoot)];
    }

    /**
     * @return list<array{module:string,tag:string,methods:list<string>,path:string,controller:string,action:string,source:string,middlewareHints:array{auth:bool,rateLimit:bool}}>
     */
    private function collectRoutesFromInterfaces(string $moduleRoot): array
    {
        $writer = new ClientWriter();
        $routes = [];
        $seen = [];

        foreach ($this->discoverRouteGroupInterfaces($moduleRoot) as $ifaceFqcn) {
            if (!$writer->hasApiMethods($ifaceFqcn)) {
                continue;
            }
            $iface = new ReflectionClass($ifaceFqcn);
            $module = $this->moduleNameFromInterface($iface);
            $tag = $this->tagFromInterface($iface);
            $groupAttrs = $iface->getAttributes(RouteGroup::class);
            if ($groupAttrs === []) {
                continue;
            }
            /** @var RouteGroup $group */
            $group = $groupAttrs[0]->newInstance();
            $prefix = '/' . trim($group->prefix, '/');

            foreach ($iface->getMethods(ReflectionMethod::IS_PUBLIC) as $method) {
                if ($method->isStatic()) {
                    continue;
                }
                $routeAttrs = $method->getAttributes(Route::class);
                if ($routeAttrs === []) {
                    continue;
                }
                /** @var Route $route */
                $route = $routeAttrs[0]->newInstance();
                $verb = strtoupper($route->method);
                $path = $route->path;
                if ($path === '' || !str_starts_with($path, '/')) {
                    continue;
                }
                $fullPath = rtrim($prefix, '/') . $path;
                $dedupeKey = $verb . ' ' . $fullPath;
                if (isset($seen[$dedupeKey])) {
                    continue;
                }
                $seen[$dedupeKey] = true;

                $routes[] = [
                    'module' => $module,
                    'tag' => $tag,
                    'methods' => [$verb],
                    'path' => $fullPath,
                    'controller' => $ifaceFqcn,
                    'action' => $method->getName(),
                    'source' => 'interface',
                    'middlewareHints' => ['auth' => false, 'rateLimit' => false],
                ];
            }
        }

        usort($routes, static function (array $a, array $b): int {
            return [$a['path'], $a['action']] <=> [$b['path'], $b['action']];
        });

        return $routes;
    }

    /**
     * @return list<string>
     */
    private function discoverRouteGroupInterfaces(string $scanRoot): array
    {
        $out = [];
        $iterator = new \RecursiveIteratorIterator(new \RecursiveDirectoryIterator($scanRoot));
        foreach ($iterator as $info) {
            if (!$info->isFile() || $info->getExtension() !== 'php') {
                continue;
            }
            $path = $info->getPathname();
            if (str_contains(str_replace('\\', '/', $path), '/Client/')) {
                continue;
            }
            $code = file_get_contents($path);
            if ($code === false || !preg_match('/\binterface\s+(\w+)/', $code, $m)) {
                continue;
            }
            if (!preg_match('/namespace\s+([^;]+);/', $code, $ns)) {
                continue;
            }
            $fqcn = trim($ns[1]) . '\\' . $m[1];
            if (!interface_exists($fqcn)) {
                continue;
            }
            $ref = new ReflectionClass($fqcn);
            if ($ref->getAttributes(RouteGroup::class) !== []) {
                $out[] = $fqcn;
            }
        }
        sort($out);

        return $out;
    }

    private function moduleNameFromInterface(ReflectionClass $iface): string
    {
        $file = str_replace('\\', '/', $iface->getFileName() ?: '');
        if (preg_match('#/Module/([^/]+)/Interface/#', $file, $m)) {
            return $m[1];
        }

        return 'Api';
    }

    private function tagFromInterface(ReflectionClass $iface): string
    {
        foreach ($iface->getAttributes(ApiController::class) as $attr) {
            try {
                $ctrl = $attr->newInstance();
                $desc = trim($ctrl->getDescription());
                if ($desc !== '') {
                    return $desc;
                }
            } catch (\Throwable) {
            }
        }

        return $iface->getShortName();
    }

    /**
     * @param list<array{module:string,tag:string,methods:list<string>,path:string,controller:string,action:string,source:string,middlewareHints:array{auth:bool,rateLimit:bool}}> $routes
     * @return array<string, mixed>
     */
    private function buildOpenApiDocument(string $module, array $routes): array
    {
        [$title, $description, $version] = $this->resolveDocumentInfo($module);

        $paths = [];
        usort($routes, static function (array $a, array $b): int {
            return [$a['path'], implode(',', $a['methods']), $a['controller'], $a['action']]
                <=> [$b['path'], implode(',', $b['methods']), $b['controller'], $b['action']];
        });

        $seenOps = [];
        foreach ($routes as $route) {
            foreach ($route['methods'] as $method) {
                $verb = strtolower($method);
                $opKey = $verb . ' ' . $route['path'];
                if (isset($seenOps[$opKey])) {
                    continue;
                }
                $seenOps[$opKey] = true;
                $paths[$route['path']][$verb] = $this->buildOperation($route, strtoupper($method));
            }
        }

        return [
            'openapi' => '3.0.3',
            'info' => [
                'title' => $title,
                'description' => $description,
                'version' => $version,
            ],
            'paths' => $paths,
        ];
    }

    /**
     * @return array{0: string, 1: string, 2: string}
     */
    private function resolveDocumentInfo(string $module): array
    {
        $meta = $this->moduleMeta[$module] ?? $this->moduleMeta[strtolower($module)] ?? [];
        $moduleTitle = trim((string)($meta['title'] ?? ''));
        $moduleDescription = trim((string)($meta['description'] ?? ''));

        $globalTitle = trim($this->apiDocConfig['title']);
        $globalDescription = trim($this->apiDocConfig['description']);
        $version = trim($this->apiDocConfig['version']) !== ''
            ? trim($this->apiDocConfig['version'])
            : self::DEFAULT_VERSION;

        if ($globalTitle !== '') {
            $title = $globalTitle;
        } elseif ($moduleTitle !== '') {
            $title = $moduleTitle;
        } else {
            $template = trim($this->apiDocConfig['default_title_template']) !== ''
                ? $this->apiDocConfig['default_title_template']
                : self::DEFAULT_TITLE_TEMPLATE;
            $title = str_replace(
                ['{app}', '{module}', '{App}', '{Module}'],
                [$this->appName, $module, $this->appName, $module],
                $template
            );
        }

        if ($globalDescription !== '') {
            $description = $globalDescription;
        } elseif ($moduleDescription !== '') {
            $description = $moduleDescription;
        } else {
            $description = self::DEFAULT_DESCRIPTION;
        }

        return [$title, $description, $version];
    }

    /**
     * @param array{module:string,tag:string,methods:list<string>,path:string,controller:string,action:string,source:string,middlewareHints:array{auth:bool,rateLimit:bool}} $route
     * @return array<string, mixed>
     */
    private function buildOperation(array $route, string $method): array
    {
        $hints = $route['middlewareHints'] ?? ['auth' => false, 'rateLimit' => false];
        $operation = [
            'tags' => [$route['tag']],
            'summary' => $route['action'],
            'operationId' => $this->operationId($method, $route['controller'], $route['action']),
        ];

        if (!interface_exists($route['controller']) || !method_exists($route['controller'], $route['action'])) {
            $operation['summary'] = strtoupper($method) . ' ' . $route['path'];
            $operation['responses'] = $this->responseObject(
                $this->standardResponseSchema(['nullable' => true]),
                $hints
            );
            return $operation;
        }

        $reflection = new ReflectionMethod($route['controller'], $route['action']);
        [$summary, $description] = $this->resolveOperationText($reflection, $method, $route['path'], $route['action']);
        $operation['summary'] = $summary;
        if ($description !== '') {
            $operation['description'] = $description;
        }

        [$requestBody, $parameters] = $this->buildRequestSpec($reflection, $method);
        if ($parameters !== []) {
            $operation['parameters'] = $parameters;
        }
        if ($requestBody !== null) {
            $operation['requestBody'] = $requestBody;
        }

        $operation['responses'] = $this->responseObject($this->buildReturnDataSchema($reflection), $hints);

        return $operation;
    }

    /**
     * @return array{0: ?array<string, mixed>, 1: list<array<string, mixed>>}
     */
    private function buildRequestSpec(ReflectionMethod $method, string $httpMethod): array
    {
        $requestClass = null;
        $parameters = [];

        foreach ($method->getParameters() as $parameter) {
            $className = $this->firstClassType($parameter->getType());
            if ($className !== null && is_a($className, BaseRequest::class, true)) {
                $requestClass = $className;
                continue;
            }

            if ($className === null) {
                $parameters[] = $this->buildScalarParameter($parameter);
            }
        }

        $requestBody = null;
        if ($requestClass !== null) {
            if ($this->usesQueryForRequest($httpMethod)) {
                $parameters = array_merge($parameters, $this->buildQueryParametersFromRequest($requestClass));
            } else {
                $requestBody = [
                    'required' => true,
                    'content' => [
                        'application/json' => [
                            'schema' => $this->classSchema($requestClass),
                        ],
                    ],
                ];
            }
        }

        return [$requestBody, $parameters];
    }

    private function usesQueryForRequest(string $httpMethod): bool
    {
        return in_array(strtoupper($httpMethod), self::QUERY_HTTP_METHODS, true);
    }

    /**
     * @return list<array<string, mixed>>
     */
    private function buildQueryParametersFromRequest(string $requestClass): array
    {
        $schema = $this->classSchema($requestClass);
        $required = [];
        foreach ($schema['required'] ?? [] as $name) {
            if (is_string($name)) {
                $required[$name] = true;
            }
        }

        $parameters = [];
        foreach ($schema['properties'] ?? [] as $name => $propSchema) {
            if (!is_string($name) || !is_array($propSchema)) {
                continue;
            }
            $description = '';
            if (isset($propSchema['description']) && is_string($propSchema['description'])) {
                $description = $propSchema['description'];
                unset($propSchema['description']);
            }
            $param = [
                'name' => $name,
                'in' => 'query',
                'required' => isset($required[$name]),
                'schema' => $propSchema,
            ];
            if ($description !== '') {
                $param['description'] = $description;
            }
            $parameters[] = $param;
        }

        return $parameters;
    }

    /**
     * @return array<string, mixed>
     */
    private function buildScalarParameter(ReflectionParameter $parameter): array
    {
        return [
            'name' => $parameter->getName(),
            'in' => 'query',
            'required' => !$parameter->isDefaultValueAvailable() && !$parameter->allowsNull(),
            'schema' => $this->schemaFromReflectionType($parameter->getType()),
        ];
    }

    /**
     * @return array<string, mixed>
     */
    private function buildReturnDataSchema(ReflectionMethod $method): array
    {
        $type = $method->getReturnType();
        $className = $this->firstClassType($type);
        if ($className !== null) {
            if (is_a($className, BaseResponse::class, true)) {
                return $this->responseDataSchema($className);
            }

            return $this->classSchema($className);
        }

        return $this->schemaFromReflectionType($type);
    }

    /**
     * @return array<string, mixed>
     */
    private function responseDataSchema(string $responseClass): array
    {
        if (!class_exists($responseClass)) {
            return ['nullable' => true];
        }

        try {
            $rc = new ReflectionClass($responseClass);
        } catch (\ReflectionException) {
            return ['nullable' => true];
        }

        if ($rc->hasProperty('data')) {
            return $this->schemaFromProperty($rc->getProperty('data'), []);
        }

        if ($rc->hasMethod('getData')) {
            $method = $rc->getMethod('getData');
            if ($method->getDeclaringClass()->getName() !== BaseResponse::class) {
                $returnType = $method->getReturnType();
                $className = $this->firstClassType($returnType);
                if ($className !== null) {
                    return $this->classSchema($className);
                }
                if ($returnType instanceof ReflectionNamedType && $returnType->isBuiltin() && $returnType->getName() !== 'array') {
                    return $this->schemaFromReflectionType($returnType);
                }
            }
        }

        return $this->classSchema($responseClass);
    }

    /**
     * @param array<string, mixed> $dataSchema
     * @return array<string, mixed>
     */
    private function standardResponseSchema(array $dataSchema): array
    {
        return [
            'type' => 'object',
            'properties' => [
                'code' => [
                    'type' => 'integer',
                    'example' => 0,
                ],
                'msg' => [
                    'type' => 'string',
                    'example' => 'success',
                ],
                'trace_id' => [
                    'type' => 'string',
                    'example' => '',
                ],
                'data' => $dataSchema,
            ],
            'required' => ['code', 'msg', 'trace_id', 'data'],
        ];
    }

    /**
     * @param array<string, mixed> $dataSchema
     * @param array{auth?: bool, rateLimit?: bool} $hints
     * @return array<string, mixed>
     */
    private function responseObject(array $dataSchema, array $hints = []): array
    {
        $responses = [
            '200' => [
                'description' => 'success',
                'content' => [
                    'application/json' => [
                        'schema' => $this->standardResponseSchema($dataSchema),
                    ],
                ],
            ],
            '400' => [
                'description' => 'validation failed',
                'content' => [
                    'application/json' => [
                        'schema' => $this->errorEnvelopeSchema(-1, 'validation failed'),
                    ],
                ],
            ],
        ];

        if (!empty($hints['auth'])) {
            $responses['401'] = [
                'description' => 'unauthenticated',
                'content' => [
                    'application/json' => [
                        'schema' => $this->errorEnvelopeSchema(401, 'Unauthenticated'),
                    ],
                ],
            ];
        }

        if (!empty($hints['rateLimit'])) {
            $responses['429'] = [
                'description' => 'too many requests',
                'content' => [
                    'application/json' => [
                        'schema' => $this->errorEnvelopeSchema(429, 'Too Many Requests'),
                    ],
                ],
            ];
        }

        return $responses;
    }

    /**
     * @return array<string, mixed>
     */
    private function errorEnvelopeSchema(int $code, string $msg): array
    {
        return [
            'type' => 'object',
            'properties' => [
                'code' => [
                    'type' => 'integer',
                    'example' => $code,
                ],
                'msg' => [
                    'type' => 'string',
                    'example' => $msg,
                ],
                'trace_id' => [
                    'type' => 'string',
                    'example' => '',
                ],
                'data' => [
                    'nullable' => true,
                ],
            ],
            'required' => ['code', 'msg', 'trace_id', 'data'],
        ];
    }

    /**
     * @param array<string, bool> $seen
     * @return array<string, mixed>
     */
    private function classSchema(string $className, array $seen = []): array
    {
        if (!class_exists($className)) {
            return ['type' => 'object'];
        }
        if (isset($seen[$className])) {
            return ['type' => 'object'];
        }
        $seen[$className] = true;

        try {
            $rc = new ReflectionClass($className);
        } catch (\ReflectionException) {
            return ['type' => 'object'];
        }

        $properties = [];
        $required = [];
        foreach ($rc->getProperties(ReflectionProperty::IS_PUBLIC | ReflectionProperty::IS_PROTECTED | ReflectionProperty::IS_PRIVATE) as $property) {
            if ($property->isStatic() || $property->getDeclaringClass()->getName() === BaseRequest::class) {
                continue;
            }
            if ($property->getDeclaringClass()->getName() === BaseResponse::class) {
                continue;
            }

            $schema = $this->schemaFromProperty($property, $seen);
            $description = $this->apiPropertyDescription($property);
            if ($description !== '') {
                $schema['description'] = $description;
            }
            $properties[$property->getName()] = $schema;

            if ($this->isRequiredProperty($property)) {
                $required[] = $property->getName();
            }
        }

        $schema = [
            'type' => 'object',
            'properties' => $properties,
        ];
        if ($required !== []) {
            $schema['required'] = $required;
        }

        return $schema;
    }

    /**
     * @param array<string, bool> $seen
     * @return array<string, mixed>
     */
    private function schemaFromProperty(ReflectionProperty $property, array $seen): array
    {
        if ($property->getAttributes(IntToString::class) !== []) {
            return ['type' => 'string'];
        }
        if ($property->getAttributes(StringToInt::class) !== []) {
            return ['type' => 'integer'];
        }

        $validation = $this->validationRule($property);
        if ($validation !== null) {
            $itemClass = $validation->getItemClass();
            if ($itemClass !== '' && class_exists($itemClass)) {
                return [
                    'type' => 'array',
                    'items' => $this->classSchema($itemClass, $seen),
                ];
            }

            if ($this->ruleContains($validation->getRule(), 'array')) {
                return [
                    'type' => 'array',
                    'items' => $this->schemaFromRule($validation->getItemRule() !== '' ? $validation->getItemRule() : 'string'),
                ];
            }
        }

        foreach ($property->getAttributes(ArrayList::class) as $attr) {
            try {
                $arrayList = $attr->newInstance();
            } catch (\Throwable) {
                continue;
            }
            $itemClass = $arrayList->getItemClass();
            if ($itemClass !== '' && class_exists($itemClass)) {
                return [
                    'type' => 'array',
                    'items' => $this->classSchema($itemClass, $seen),
                ];
            }
        }

        $className = $this->firstClassType($property->getType());
        if ($className !== null) {
            $arrayStructSchema = $this->arrayStructSchema($className);
            if ($arrayStructSchema !== null) {
                return $this->applyNullableFlag($arrayStructSchema, $property->getType());
            }

            return $this->classSchema($className, $seen);
        }

        $schema = $this->schemaFromReflectionType($property->getType());
        if (($schema['type'] ?? null) === 'array') {
            $docItem = $this->docblockArrayItemSchema($property, $seen);
            if ($docItem !== null) {
                $schema['items'] = $docItem;
            }
        }

        return $schema;
    }

    /**
     * @return array<string, mixed>
     */
    private function schemaFromReflectionType(?ReflectionType $type): array
    {
        if ($type === null) {
            return ['nullable' => true];
        }

        if ($type instanceof ReflectionUnionType) {
            $schema = ['nullable' => $type->allowsNull()];
            foreach ($type->getTypes() as $namedType) {
                if ($namedType instanceof ReflectionNamedType && $namedType->getName() !== 'null') {
                    $schema = array_merge($schema, $this->schemaFromNamedType($namedType));
                    break;
                }
            }
            return $schema;
        }

        if ($type instanceof ReflectionNamedType) {
            $schema = $this->schemaFromNamedType($type);
            if ($type->allowsNull()) {
                $schema['nullable'] = true;
            }
            return $schema;
        }

        return ['nullable' => true];
    }

    /**
     * @return array<string, mixed>
     */
    private function schemaFromNamedType(ReflectionNamedType $type): array
    {
        if (!$type->isBuiltin()) {
            $arrayStructSchema = $this->arrayStructSchema($type->getName());
            if ($arrayStructSchema !== null) {
                return $arrayStructSchema;
            }

            return $this->classSchema($type->getName());
        }

        return $this->schemaFromRule($type->getName());
    }

    /**
     * ArrayInteger / ArrayString 在 OpenAPI 中按数组描述，而非 object。
     *
     * @return array<string, mixed>|null
     */
    private function arrayStructSchema(string $className): ?array
    {
        if (is_a($className, ArrayInteger::class, true)) {
            return [
                'type' => 'array',
                'items' => ['type' => 'integer'],
            ];
        }

        if (is_a($className, ArrayString::class, true)) {
            return [
                'type' => 'array',
                'items' => ['type' => 'string'],
            ];
        }

        return null;
    }

    /**
     * @param array<string, mixed> $schema
     * @return array<string, mixed>
     */
    private function applyNullableFlag(array $schema, ?ReflectionType $type): array
    {
        if ($type !== null && $type->allowsNull()) {
            $schema['nullable'] = true;
        }

        return $schema;
    }

    /**
     * @return array<string, mixed>
     */
    private function schemaFromRule(string $rule): array
    {
        $tokens = $this->ruleTokens($rule);
        foreach ($tokens as $token) {
            if (in_array($token, ['integer', 'int'], true)) {
                return ['type' => 'integer'];
            }
            if ($token === 'number' || $token === 'float' || $token === 'double') {
                return ['type' => 'number'];
            }
            if (in_array($token, ['boolean', 'bool'], true)) {
                return ['type' => 'boolean'];
            }
            if ($token === 'array') {
                return [
                    'type' => 'array',
                    'items' => ['type' => 'string'],
                ];
            }
            if ($token === 'object') {
                return ['type' => 'object'];
            }
            if ($token === 'null') {
                return ['nullable' => true];
            }
        }

        return ['type' => 'string'];
    }

    /**
     * @param array<string, bool> $seen
     * @return ?array<string, mixed>
     */
    private function docblockArrayItemSchema(ReflectionProperty $property, array $seen): ?array
    {
        $doc = $property->getDocComment();
        if ($doc === false || $doc === '') {
            return null;
        }
        if (!preg_match('/@var\s+array\s*<\s*(?:int|string)\s*,\s*([^>|]+)(?:\|[^>]*)?>/i', $doc, $match)
            && !preg_match('/@var\s+array\s*<\s*([^>|]+)(?:\|[^>]*)?>/i', $doc, $match)
        ) {
            return null;
        }

        $inner = trim($match[1]);
        if ($inner === '') {
            return null;
        }
        $ruleSchema = $this->schemaFromRule($inner);
        if (($ruleSchema['type'] ?? null) !== 'string' || in_array(strtolower($inner), ['string'], true)) {
            return $ruleSchema;
        }

        $className = $this->resolveDocblockClass($property, $inner);
        if ($className !== null) {
            return $this->classSchema($className, $seen);
        }

        if (strtolower($inner) === 'mixed') {
            return ['nullable' => true];
        }

        return null;
    }

    private function resolveDocblockClass(ReflectionProperty $property, string $type): ?string
    {
        $type = ltrim(trim($type), '\\');
        if ($type === '' || in_array(strtolower($type), ['int', 'integer', 'string', 'float', 'bool', 'boolean', 'array', 'mixed'], true)) {
            return null;
        }
        if (class_exists($type)) {
            return $type;
        }

        $namespace = $property->getDeclaringClass()->getNamespaceName();
        if ($namespace !== '') {
            $candidate = $namespace . '\\' . $type;
            if (class_exists($candidate)) {
                return $candidate;
            }
        }

        return null;
    }

    /**
     * @return array{0: string, 1: string} [summary, description]
     */
    private function resolveOperationText(
        ReflectionMethod $method,
        string $httpMethod,
        string $path,
        string $action
    ): array {
        $apiSummary = '';
        $apiDescription = '';
        foreach ($method->getAttributes(ApiOperation::class) as $attr) {
            try {
                $op = $attr->newInstance();
                $apiSummary = trim($op->getSummary());
                $apiDescription = trim($op->getDescription());
            } catch (\Throwable) {
                $apiSummary = '';
                $apiDescription = '';
            }
            break;
        }

        $summary = $apiSummary !== '' ? $apiSummary : $apiDescription;
        if ($summary === '') {
            $summary = $this->phpDocSummary($method);
        }
        if ($summary === '') {
            $summary = strtoupper($httpMethod) . ' ' . $path;
        }
        if ($summary === '') {
            $summary = $action;
        }

        $description = '';
        if ($apiSummary !== '' && $apiDescription !== '' && $apiDescription !== $apiSummary) {
            $description = $apiDescription;
        }

        return [$summary, $description];
    }

    private function phpDocSummary(ReflectionMethod $method): string
    {
        $doc = $method->getDocComment();
        if ($doc === false || $doc === '') {
            return '';
        }

        // CR/LF only — bare /\R/ without /u matches byte 0x85 (NEL) and splits UTF-8 Chinese (入/内).
        foreach (preg_split('/\r\n|\n|\r/', $doc) ?: [] as $line) {
            $line = trim((string)$line);
            $line = preg_replace('/^\s*\*\s?/', '', $line) ?? $line;
            $line = trim($line);
            if ($line === '' || str_starts_with($line, '/**') || str_starts_with($line, '*/') || str_starts_with($line, '@')) {
                continue;
            }

            return $line;
        }

        return '';
    }

    private function apiPropertyDescription(ReflectionProperty $property): string
    {
        foreach ($property->getAttributes(ApiProperty::class) as $attr) {
            try {
                return $attr->newInstance()->getDescription();
            } catch (\Throwable) {
                return '';
            }
        }

        return '';
    }

    private function validationRule(ReflectionProperty $property): ?ValidationRule
    {
        foreach ($property->getAttributes(ValidationRule::class) as $attr) {
            try {
                return $attr->newInstance();
            } catch (\Throwable) {
                return null;
            }
        }

        return null;
    }

    private function isRequiredProperty(ReflectionProperty $property): bool
    {
        $validation = $this->validationRule($property);
        if ($validation === null) {
            return false;
        }

        $tokens = $this->ruleTokens($validation->getRule());
        foreach (['required', 'require', 'must'] as $requiredRule) {
            if (in_array($requiredRule, $tokens, true)) {
                return true;
            }
        }

        return false;
    }

    private function ruleContains(string $rule, string $token): bool
    {
        return in_array(strtolower($token), $this->ruleTokens($rule), true);
    }

    /**
     * @return list<string>
     */
    private function ruleTokens(string $rule): array
    {
        $tokens = preg_split('/[|,\s:]+/', strtolower($rule), -1, PREG_SPLIT_NO_EMPTY);
        return array_values(array_unique($tokens ?: []));
    }

    private function operationId(string $method, string $controller, string $action): string
    {
        $short = str_contains($controller, '\\') ? substr($controller, strrpos($controller, '\\') + 1) : $controller;
        return strtolower($method) . $short . ucfirst($action);
    }

    private function firstClassType(?ReflectionType $type): ?string
    {
        if ($type === null) {
            return null;
        }
        if ($type instanceof ReflectionNamedType) {
            return $type->isBuiltin() ? null : $type->getName();
        }
        if ($type instanceof ReflectionUnionType) {
            foreach ($type->getTypes() as $namedType) {
                if ($namedType instanceof ReflectionNamedType && !$namedType->isBuiltin()) {
                    return $namedType->getName();
                }
            }
        }

        return null;
    }

    /**
     * @return array<string, array{title?: string, description?: string}>
     */
    private function loadModuleMeta(string $packageRoot): array
    {
        $candidates = [
            $packageRoot . DIRECTORY_SEPARATOR . 'openapi-modules.json',
            $this->projectRoot . DIRECTORY_SEPARATOR . 'App' . DIRECTORY_SEPARATOR . 'Router' . DIRECTORY_SEPARATOR . 'api_router_module.json',
        ];
        $file = null;
        foreach ($candidates as $candidate) {
            if (is_file($candidate)) {
                $file = $candidate;
                break;
            }
        }
        if ($file === null) {
            return [];
        }

        $json = file_get_contents($file);
        if ($json === false) {
            return [];
        }
        $data = json_decode($json, true);
        if (!is_array($data)) {
            return [];
        }

        $out = [];
        foreach ($data as $module => $meta) {
            if (!is_string($module) || !is_array($meta)) {
                continue;
            }
            $out[$module] = [
                'title' => isset($meta['title']) ? (string)$meta['title'] : '',
                'description' => isset($meta['description']) ? (string)$meta['description'] : '',
            ];
            $out[strtolower($module)] = $out[$module];
        }

        return $out;
    }

    /**
     * @return array{title: string, description: string, version: string, default_title_template: string}
     */
    private function loadApiDocConfig(): array
    {
        $defaults = [
            'title' => '',
            'description' => '',
            'version' => self::DEFAULT_VERSION,
            'default_title_template' => self::DEFAULT_TITLE_TEMPLATE,
        ];

        $candidates = [
            $this->projectRoot . DIRECTORY_SEPARATOR . 'App' . DIRECTORY_SEPARATOR . 'Config' . DIRECTORY_SEPARATOR . 'apidoc.php',
        ];

        $file = null;
        foreach ($candidates as $candidate) {
            if (is_file($candidate)) {
                $file = $candidate;
                break;
            }
        }
        if ($file === null) {
            return $defaults;
        }

        $data = require $file;
        if (!is_array($data)) {
            return $defaults;
        }
        $section = isset($data['apidoc']) && is_array($data['apidoc']) ? $data['apidoc'] : $data;

        return [
            'title' => isset($section['title']) ? (string)$section['title'] : '',
            'description' => isset($section['description']) ? (string)$section['description'] : '',
            'version' => isset($section['version']) && (string)$section['version'] !== ''
                ? (string)$section['version']
                : self::DEFAULT_VERSION,
            'default_title_template' => isset($section['default_title_template']) && (string)$section['default_title_template'] !== ''
                ? (string)$section['default_title_template']
                : self::DEFAULT_TITLE_TEMPLATE,
        ];
    }

    private function resolveAppName(): string
    {
        $serviceKey = trim(str_replace('\\', '/', $this->serviceKey), '/');
        $parts = explode('/', $serviceKey);
        $project = $parts[0] ?? '';

        return $project !== '' ? $project : 'App';
    }

    private function ensureDir(string $path): void
    {
        if (is_dir($path)) {
            return;
        }
        if (is_file($path)) {
            throw new \RuntimeException("[generate-openapi] Cannot create directory {$path}: a regular file exists at this path.");
        }
        if (!@mkdir($path, 0755, true) && !is_dir($path)) {
            throw new \RuntimeException("[generate-openapi] mkdir failed: {$path}");
        }
    }

    private function cleanGeneratedOpenApiFiles(): void
    {
        $files = glob($this->outputDir . DIRECTORY_SEPARATOR . 'openapi-*.yaml') ?: [];
        foreach ($files as $file) {
            if (is_file($file)) {
                @unlink($file);
            }
        }
    }
}
